# Generated by Django 5.2.17 on 2026-09-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenth_collage', models.CharField(max_length=100)),
                ('tenth_Board', models.CharField(max_length=100)),
                ('tenth_passing_year', models.IntegerField()),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_collage', models.CharField(max_length=100)),
                ('twelfth_Board', models.CharField(max_length=100)),
                ('twelfth_passing_year', models.IntegerField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.admissionapplication')),
            ],
        ),
    ]
