# Generated by Django 5.2.17 on 2026-09-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_academicdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdetails',
            old_name='tenth_Board',
            new_name='tenth_board',
        ),
        migrations.RenameField(
            model_name='academicdetails',
            old_name='twelfth_Board',
            new_name='twelfth_board',
        ),
    ]
