# Generated by Django 5.2.17 on 2026-09-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_rename_tenth_board_academicdetails_tenth_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
