# Generated by Django 5.2.17 on 2026-09-07 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_admissionapplication_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='documents/photos/')),
                ('signature', models.ImageField(upload_to='documents/signature/')),
                ('tenth_marksheet', models.ImageField(upload_to='documents/tenth_marksheet/')),
                ('twelth_marksheet', models.ImageField(upload_to='documents/twelth_marksheet/')),
                ('leaving_certificate', models.ImageField(upload_to='documents/leaving_certificate/')),
                ('caste_certificate', models.ImageField(blank=True, null=True, upload_to='documents/caste_certificate/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.admissionapplication')),
            ],
        ),
    ]
