# Generated by Django 5.2.17 on 2026-09-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_studentdocuments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdocuments',
            old_name='twelth_marksheet',
            new_name='twelfth_marksheet',
        ),
    ]
