# Generated by Django 5.2.17 on 2026-09-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('duration', models.IntegerField(help_text='Duration In Years')),
                ('total_seats', models.IntegerField(default=0)),
                ('available_seats', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
